tmux:
  symbols:
    branch: '󰘬 '
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: ' '
    conflict: ' '
    modified: ' '
    untracked: '󰼈 '
    stashed: ' '
    clean: 
  styles:
    clear: '#[fg=default]'
    state: '#[fg=red,bold]'
    branch: '#[fg=white,bold]'
    remote: '#[fg=cyan]'
    staged: '#[fg=#00BB00,bold]'
    conflict: '#[fg=red,bold]'
    modified: '#[fg=gold,bold]'
    untracked: '#[fg=darkgrey,bold]'
    stashed: '#[fg=cyan,bold]'
    clean: '#[fg=#00BB00,bold]'
  layout: [branch, divergence, ' - ', flags]
  options:
    branch_max_len: 0
